### PR TITLE
Added an amazing page!

### PR DESCRIPTION
**Pull request by KaceyGambill**

### CODE REVIEW

**Comment by Tor020** [comment]
Please add a link on the main directory to your page and resubmit you pull request :+1:

**Comment by KaceyGambill** [comment]
Added the link to home dir!

**Comment by Tor020** [comment]
Almost there m8. How do people get to your page?

I made a gif to illustrate the problem
https://gyazo.com/33aa45d3f1d0726146d9479001350aa0

You haven't added a link to your page from the primary directory. The primary directory is the index.html page

**Comment by KaceyGambill** [comment]
Whoops!!
I see what you’re saying, my bad. Thanks a lot for the help still getting the hang of using GitHub :D

**Pull request merged**
